language: python
python:
  - "3.4"

before_install:
  - sudo add-apt-repository ppa:gns3/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install dynamips
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
    
install:
  - python setup.py install
  - pip install -rdev-requirements.txt

script:
    - ifconfig
    - py.test -v -s tests --cov gns3server --cov-report term-missing

#branches:
#  only:
#    - master

notifications:
  email:
    - julien@gns3.net
#  irc:
#    channels:
#      - "chat.freenode.net#gns3"
#    on_success: change
#    on_failure: always

after_success:
  - coveralls --data_file .coverage --base_dir gns3server
